<?php session_start();?>
<!DOCTYPE html>
<html>
<head>
<title>Boxeon fees </title>
<?php require_once("../meta.html");?>
</head>
<body id="discounts">
<div id="container">
  <?php require_once("../header.php");?>
  <div id="masthead">
    <section id="headline">
		<p class="text-heading-label">BEAT OUR COMMISSION</p>
      <h1 class='ginormous'>Your super power is your network</h1>
      <p id="pitch">We take 14% from the revenue generated by creators not in the partner program, but you can beat this rate down to 5% by inviting creators you know to Boxeon.</p>
		<a class="button" href="<?php require_once "../signin/create-url.php"; echo $client->createAuthUrl(); ?>">Get started</a>
      <a href="#whatis" class="button clearbtn">Learn more</a> </section>
    <div id="masthead-image-commission"> </div>
  </div>
  <main> <a id='whatis' href='#whatis'></a>
    <aside id="business-model-explanation">
      <h1 class="extra-large-font darkblue">How it works</h1>
      <p class="centered font-1-5-em">Get Started by inventing creators you know. We'll automatically credit your account once they join.</p>
    </aside>
    <section class="section">
      <div class="alt-section-inner-grid">
        <div class="secinner">
          <p><span class="highlighted">11%</span> commission</p>
          <p>Get <b>three</b> content creator to join and we'll drop our commission to 11%.</p>
        </div>
        <img src="../images/powerful.svg" alt="subscription box"> </div>
    </section>
    <section class="section">
      <div class="section-inner-grid"> <img src="../images/powerful.svg" alt="subscription box">
        <div class="secinner">
          <p><span class="highlighted">8%</span> commission</p>
          <p>Get <b>six</b> total creators to join and we'll slash our commission to 8%.</p>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="alt-section-inner-grid large-margin-bottom">
        <div class="secinner">
          <p><span class="highlighted">5%</span> commission</p>
          <p>Get <b>nine</b> total creators to join and we'll drop our commission to 5%.</p>
        </div>
        <img src="../images/powerful.svg" alt="subscription box"> </div>
    </section>
    <section>
      <div class="centered margin-bottom-10-em">
        <h1 class="extra-large-font darkblue margin-top-4-em">It's that simple</h1>
        <br>
        <a class="button" href="<?php require_once "../signin/create-url.php"; echo $client->createAuthUrl(); ?>">Get started</a> </div>
    </section>
  </main>
</div>
<?php require_once("../footer.html");?>
</div>
</body>
</html>
